### ISSUE TITLE
Predictive Algorithms

### ISSUE THREAD

**Issue by diannakane** [medic/product-initiatives#38]
Use data to anticipate and identify CHWs who may experience excessively high workloads, are unlikely to meet targets, are risk of resigning, and other risks to their performance and the community's health.

https://drive.google.com/open?id=1MkKUMrAGu8pvReSHlsMMC4FfhnyNuLyv

**Comment by MaxDiz** [comment]
closing since this body of work has been advanced through IN project deployments. May be split out into separate initiatives for further improvements in the future
