### ISSUE TITLE
Supervisor reference app

### ISSUE THREAD

**Issue by smbuthia** [medic/product-initiatives#80]
Supervision and workforce management are important aspects of building and maintaining high-performing community health systems. Supervisors help Community Health Workers deliver quality healthcare services to their patients through building CHW care delivery knowledge and skills, fostering a supportive work environment, and supporting continuity of care between home-based care and community health centers or facilities.

We are building a reference application that can demonstrate how the CHT can support supervisors to continually monitor and improve program quality. This would enable them to access information about health outcomes in their supervisory area, performance outputs, and other relevant information required to supervise their CHVs.

**Comment by andrablaj** [comment]
Closing as marked as `Done`
