### ISSUE TITLE
CHT Code Health (Care Teams)

### ISSUE THREAD

**Issue by michaelkohn** [medic/product-initiatives#88]
## 2023 Q4
None planned, focusing on cybersecurity

## 2023 Q3
- [x] https://github.com/medic/cht-core/issues/7651 
- [x] https://github.com/medic/cht-core/issues/8237 
- [ ] https://github.com/medic/cht-core/issues/5613 

## 2023 Q2
- [x] https://github.com/medic/cht-core/issues/6505 
- [x] https://github.com/medic/cht-core/issues/7250 
- [x] https://github.com/medic/cht-core/issues/7651 
- [x] https://github.com/medic/cht-core/issues/8237

## 2023 Q1

- [x] https://github.com/medic/cht-core/issues/7992

**Comment by latin-panda** [comment]
This one is also part of this list: [Angular's ExpressionChangedAfterItHasBeenCheckedError exception in Reports and Contacts tabs](https://github.com/medic/cht-core/issues/8022)

**Comment by latin-panda** [comment]
Please, this one too [Hovering over dates throws error, and default tooltip is displayed](https://github.com/medic/cht-core/issues/8242) (I can't update the list from the description)

**Comment by garethbowen** [comment]
@latin-panda Thanks. Those two are actual bugs that users care about and therefore don't really fall into the description of Code Health. That's not to say they're not important but they should be tracked separately, not in this issue.

**Comment by andrablaj** [comment]
Closing as marked as `Done`
